[package]
name = "lob_router"
type = "lib"
authors = ["Oleh Misarosh <olehmisar@gmail.com>"]
compiler_version = ">=0.39.0"

[dependencies]
common = { path = "../common" }
erc20 = { path = "../erc20" }
