[package]
name = "lob_router_swap"
type = "bin"
authors = ["Oleh Misarosh <olehmisar@gmail.com>"]
compiler_version = ">=0.39.0"

[dependencies]
common = { path = "../common" }
lob_router = { path = "../lob_router" }
erc20 = { path = "../erc20" }
