[package]
name = "rollup"
type = "bin"
authors = ["Oleh Misarosh <olehmisar@gmail.com>"]
compiler_version = ">=0.39.0"

[dependencies]
protocol_types = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v0.84.0", directory = "noir-projects/noir-protocol-circuits/crates/types" }
common = { path = "../common" }
