[package]
name = "common"
type = "lib"
authors = ["Oleh Misarosh <olehmisar@gmail.com>"]

[dependencies]
protocol_types = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v3.0.1", directory = "noir-projects/noir-protocol-circuits/crates/types" }
nodash = { tag = "v0.41.2", git = "https://github.com/olehmisar/nodash/" }
